# Generated by Django 4.2.20 on 2025-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                max_length=10,
            ),
        ),
    ]
