# Generated by Django 4.2.20 on 2025-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_alter_moodentry_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
